ALTER TABLE customers ADD COLUMN tenant_id VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE customers ALTER COLUMN tenant_id DROP DEFAULT;

ALTER TABLE products ADD COLUMN tenant_id VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE products ALTER COLUMN tenant_id DROP DEFAULT;

ALTER TABLE orders ADD COLUMN tenant_id VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE orders ALTER COLUMN tenant_id DROP DEFAULT;