version: "3.9"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: bom-pedido-redis
    ports:
      - "6379:6379"

  mongo:
    image: candis/mongo-replica-set
    container_name: bom-pedido-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"

  rabbitmq:
    container_name: bom-pedido-rabbitmq
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: bom-pedido-jaeger
    network_mode: host
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: ":9411"
