version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: bom-pedido-mysql
    environment:
      MYSQL_DATABASE: bompedido
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: bom-pedido-redis
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: bom-pedido-rabbitmq
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"