name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Test coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Ignore mock and memory files from coverage
        run: cat coverage.out | grep -v '_mock.go' | grep -v '_memory.go' > coverage-test.out

      - name: Generate HTML coverage report
        run: go tool cover -html=coverage-test.out -o coverage.html

      - name: Upload html report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage.html
          retention-days: 1

      - name: Show coverage summary in console
        run: go tool cover -func=coverage-test.out

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bom-pedido-api:latest,${{ secrets.DOCKER_USERNAME }}/bom-pedido-api:${{ github.sha }}